# Generated by Django 5.2.8 on 2025-12-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('display', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('totalquantity', models.IntegerField()),
            ],
        ),
    ]
