# Generated by Django 5.2.8 on 2025-12-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
